### ISSUE TITLE
Could not found the config.json file

### ISSUE THREAD

**Issue by Sabal-Subedi** [Koon-Kiat/Spam-And-Phishing-Detection-Using-Machine-Learning#10]
I tried replicating this repo and benchmarking my model against the given models. However, I could not find the config.json file. The program did not work as you mentioned in Readme.md.

**Comment by Koon-Kiat** [comment]
```json
{
    "base_dir": "C:\\Path\\To\\Folder\\Location"
}
```

Just add in the folder path in this format in the config.json file
